apiVersion: v1
kind: Service
metadata:
  name: my-redis-app-service
spec:
  selector:
    app: my-redis-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

